### ISSUE TITLE
Hi !

### ISSUE THREAD

**Issue by ghost** [lijamez/Tonbot#1]
Sorry for my language because i'm french ^^ but i see the code of the discord bot "Tonbot" and i'm interressed by the plugin music because you play spotify music. On my bot the music don't wan't to play. Can you explain me how you do this ?

**Comment by lijamez** [comment]
Hi, I haven't had time to maintain this project. If you want to play music in your Discord server, check out other bots like FredBoat: https://fredboat.com/
